### ISSUE TITLE
codeCTRL expects u32 as json key, which is not supported in python.

### ISSUE THREAD

**Issue by svmorris** [pwnCTRL/codectrl#12]
For the `code_snippet` map codeCTRL seems to be looking for integers as keys. (I am not actually sure this is what is happening, but it seems like it from errors.) Python (and many other languages) unfortunately do not allow this, and thus it would be really hard to send this payload.

Would it be possible to either send strings as keys or send the `code_snippet` as an array of maps with a `line_number` and a `code` key.

Json that I was sending from python:
```json
{
    "message": "3  ",
    "message_type": "<class 'int'>",
    "line_number": 4,
    "code_snippet": {
        "2": "",
        "3": "",
        "4": "codectrl.log( 3)",
        "5": ""
    },
    "file_name": "/home/antone/pwnCTRL/software/codectrl-python-logger.git/main/a.py",
    "stack": [
        {
            "name": "<module>",
            "code": "codectrl.log( 3)",
            "file_path": "/home/antone/pwnCTRL/software/codectrl-python-logger.git/main/a.py",
            "line_number": 4,
            "column_number": 0
        }
    ],
    "warnings": [],
    "address": "127.0.0.1"
}
```

Error:
![Screenshot from 2021-12-23 00-26-31](https://user-images.githubusercontent.com/46561460/147166226-6ea73a09-04c6-4ffc-9e35-874e36ac311c.png)

**Comment by STBoyden** [comment]
This should have been fixed already? Can you confirm that you're on the latest commit?

**Comment by svmorris** [comment]
oh, errm the default branch is main, I was using that hahah
