### ISSUE TITLE
Potential style improvements for a better User Experience

### ISSUE THREAD

**Issue by bczsalba** [pwnCTRL/codectrl#15]
While the application is functionally really great, the common user might be confused by some of its elements.

I'll insert a screenshot to make it easier to point things out.

<img width="951" alt="Screenshot 2022-01-02 at 21 17 07" src="https://user-images.githubusercontent.com/66030897/147888372-904ec07c-5ea3-4276-9846-dccb33097352.png">

### First problem: Text sizes seem to be a bit all over the place. 

Font sizes and colors are meant to establish a sort of visual hierarchy in a design. There is 3 different levels of headers on this page, but they all use (visually) about the same font size. In addition to this, the brighter styling of some of the deeper elements (such as `Position` and `Code` in the stack trace) makes them __look__ bigger. Element font size should generally be inversely relational to its depth in the visual hierarchy, so as the element goes deeper in the chain the font size should decrease.

> Proposed solution: Use different sizes for elements with different levels of importance, and decrease visual importance (font size, how much a style stands out) as you go deeper in the hierarchy

### Second problem: Mouse interactable elements aren't highlighted well.

It is really important for a user to know what they can interact with, so they don't have to press on random things until they find something that works. While buttons are visually obvious, clickable text isn't. On websites the standard seems to be some kind of underlining for the text, and giving it a different color from the rest of the content. In `codectrl` a lot of non-clickable elements use a style that to me made them like they have some mouse functionality, while things that actually did used styles that looked to be normal body text.

For example, `Log information` uses a brighter color with underlining. This makes it feel like it should accept clicks, but it doesn't. Same thing happens with all the labels under `Details`, like `Position`. Using this style would be alright if the actually clickable content was made even more visible, but it's not. Without context and some guess work it is really difficult to figure out that `Stack trace` is clickable, though the arrow next to it is a nice touch.

> Proposed solution: Reserve brighter styles only for clickable text, but try to favor buttons over text for interactions.

### Third problem: Lack of color.

This is very much up to the user, but I think the UI could gain a lot from at least one accent color added in. Some form of syntax highlighting for the code snippets would also be immensely useful, and make the interface nicer to look at. As of right now, it looks very reminiscent of default config `ImGUI` programs, which have long been associated with "temporary UI until we find something better" in my head, though it might be different for others. Again, this is completely my opinion, so feel free to disregard it.

> Proposed solution: Add a minimal amount of color

I think that's all I could find for now. The program looks incredibly useful, and with a couple of touches it could become really nice to use as well.

**Comment by STBoyden** [comment]
I will be focusing on these improvements for the time being. Thank you!

**Comment by STBoyden** [comment]
@bczsalba Could you do another review of the changes so far?

**Comment by bczsalba** [comment]
Well I tried to but something doesn't seem to want me to.

<img width="975" alt="Screenshot 2022-01-05 at 7 10 10" src="https://user-images.githubusercontent.com/66030897/148168917-7f5af2a2-e247-4a56-811a-ac8e34063633.png">

I'm not very familiar with rust as a language, so it totally can be that I'm just doing something wrong. Little help? 😄

**Comment by STBoyden** [comment]
if you update the submodules that would fix that.

**Comment by bczsalba** [comment]
Thank you!

I tried it out, and I definitely prefer this version
<img width="1000" alt="Screenshot 2022-01-05 at 9 22 30" src="https://user-images.githubusercontent.com/66030897/148184377-8c2e7e99-042d-45f6-83ae-c1b617bec21c.png">
.

One thing I don't think I noticed before is everything seems a bit too bright. Maybe using some light grey instead of pure white for the text would make it a bit less contrast-y?

A couple of buttons seem to have misaligned themselves, but I'm pretty sure you've noticed that too. The checkbox at the top next to `Case sensitive` gets overlayed by the sorting button.

I also think there could be a bit more difference between the colors of the headers vs body text. I like the difference in size between different levels though!

Good job so far!

**Comment by STBoyden** [comment]
>One thing I don't think I noticed before is everything seems a bit too bright. Maybe using some light grey instead of pure white for the text would make it a bit less contrast-y?

Hm yeah I see your point, it is *quite* bright. I can change that.

> A couple of buttons seem to have misaligned themselves, but I'm pretty sure you've noticed that too. The checkbox at the top next to Case sensitive gets overlayed by the sorting button.

The misalignment came with the font for some reason, I can try other fonts and see if they fix that issue. However the overlay is due to how the GUI framework draws widgets, since it's immediate mode, it's difficult to pre-allocate space for widgets that "don't exist" yet, but I can try and find a work around for that.

> I also think there could be a bit more difference between the colors of the headers vs body text. I like the difference in size between different levels though!

I agree, thoughts on keeping the headers white and making the text light-gray?

> Good job so far!

:)

**Comment by bczsalba** [comment]
> I agree, thoughts on keeping the headers white and making the text light-gray?

That's about the idea I had, if it doesn't work it's not hard to play around a bit more to find something that does.

Contact me if you need feedback again, and thank you for involving me!

**Comment by STBoyden** [comment]
> Contact me if you need feedback again, and thank you for involving me!

Would it be possible for you to have a look again?

**Comment by bczsalba** [comment]
It looks much better!

The top bar looks great, and I enjoy the additional monospacing to highlight some text.

I don't know if this has been there already, but I like the idea of having the hover tooltip over the code example on the right, but I think it could be styled to feel like more of a hint. It feels a bit too prominent with these colors, **maybe make it either transparent or lighter grey?**

I also love the use of accent colors over buttons! I'm not sure if it's just me, but it looks like the accent color is more saturated in the about tabs.

Is "Listening on" supposed to be a grey? If you made it grey to not blend in so much with all the headers under it, I think you could put it to the bar above, as I feel like a user doesn't need to look at it too often. Here is a quick mockup:

<img width="1000" alt="Screenshot 2022-01-07 at 8 19 22" src="https://user-images.githubusercontent.com/66030897/148507321-70d039f0-4e4c-4fe1-a952-db87058f359f.png">

My "tooling" didn't allow me to move all the logs up into the now unused space, but if you did that I think the overall look would improve a good bit.

**Comment by STBoyden** [comment]
> I don't know if this has been there already, but I like the idea of having the hover tooltip over the code example on the right,

It wasn't there already, I decided to add that not too long ago. 

> but I think it could be styled to feel like more of a hint. It feels a bit too prominent with these colors, maybe make it either transparent or lighter grey?

I will try and implement this, unfortunately per-component styling can be a little annoying to do. I have reduced the shadow and it seems less prominent:

![image](https://user-images.githubusercontent.com/25185976/148622521-3a85ca06-4c93-48fe-8fd3-862fb454da6d.png)

How does that look?

> I also love the use of accent colors over buttons! I'm not sure if it's just me, but it looks like the accent color is more saturated in the about tabs.

The more saturated colour is the "selected colour" whereas the colour that is used when interactable things are hovered is the "hover colour". Would it be better if they were the same colour?

**Comment by bczsalba** [comment]
That looks great! Though I think I would add some extra padding to the top, as it blends in a bit too much with the header bar.

> The more saturated colour is the "selected colour" whereas the colour that is used when interactable things are hovered is the "hover colour". Would it be better if they were the same colour?

For me logically it would, but I'm not quite sure. It felt a bit weird seeing the more saturated color, as I didn't remember seeing it anywhere else.

**Comment by STBoyden** [comment]
> That looks great! Though I think I would add some extra padding to the top, as it blends in a bit too much with the header bar.

I don't get that on my system, could you provide a screenshot?

> For me logically it would, but I'm not quite sure. It felt a bit weird seeing the more saturated color, as I didn't remember seeing it anywhere else.

I'll try and play with the values, maybe make it less of a jarring change?

> Edit: Looking back, I think I may have preferred the two top bars being separate. That way the icons were larger, and there was a bit more breathing room for everything. The listening label fit in nicely to the side as well, so it wasn't taking up an entire row itself.

Me too, I will place them in the same row and have it wrap to the next line if the window's width is too narrow.

**Comment by bczsalba** [comment]
So I'm not quite sure how much changed compared to your last comment, but here is what I see on the latest commit.

<img width="1000" alt="Screenshot 2022-01-15 at 21 22 04" src="https://user-images.githubusercontent.com/66030897/149636572-1353cca9-484a-41cd-8859-9a431501e3b0.png">

With the two bars, I meant the `File`, `Help`... line and all the sorting information. It seems you have done basically the exact thing I was suggesting, so that's great!

One thing though, I think having the `Listening on` label aligned to the right would make the screen feel more... balanced? I hope that makes sense.

And another, misc. thing: When hovering on the code snippet, it says "Right-click to open...". For a lot of machines, Macs specifically it might not be a right click, for example on my machine it's a two-finger tap. I think having "Secondary-click" there would make it a bit more universal in general, but its somewhat wordy.

While we are in that part of the UI, would it be possible to put a `" "` between the line number and the indicator? In the screenshot, that would be 
```
   4   def main():
>> 5         codectrl.log()` 
```
from

```
  4   def main():
>>5         codectrl.log()
```

Otherwise the program is really great to use at this moment, and I'm really happy with all the changes that have been made. Good job!

**Comment by STBoyden** [comment]
> One thing though, I think having the Listening on label aligned to the right would make the screen feel more... balanced? I hope that makes sense.

Unfortunately, due to limitations of the GUI framework we're using we can't "pre-allocate" space very easily due to the way immediate mode GUI's works. It's possible but a bit of a pain and ugly in the code. I do agree though, I'll probably put a pin in this to do this at a later point.

> And another, misc. thing: When hovering on the code snippet, it says "Right-click to open...". For a lot of machines, Macs specifically it might not be a right click, for example on my machine it's a two-finger tap. I think having "Secondary-click" there would make it a bit more universal in general, but its somewhat wordy.

I agree, and I implemented that in one of the commits since you've posted this reply.

> While we are in that part of the UI, would it be possible to put a " " between the line number and the indicator?

I agree that this would be better but I'll put a pin in this for similar reasons explained earlier.

> Otherwise the program is really great to use at this moment, and I'm really happy with all the changes that have been made. Good job!

Thank you! I'm pretty much ready to merge this into `devel` then back into `main`, but I'd like to get your final opinion. Additionally, if possible could you check the the opening/saving dialogs work on macOS? Unfortunately, I don't have a macOS machine on me to test this on. There's an active issue about it (#18), so if you encounter that, don't worry I am aware.

**Comment by STBoyden** [comment]
Additionally, I would like to ask if you would be willing to be credited for your help? If so, what details should I use?

**Comment by bczsalba** [comment]
Hey!

So I'm currently having some odd issues with the python logger, but I'll test out the dialogues once I figure that out. Overall I think you implemented every one of the things that would improve the project, and I think it looks and feels great to use now. The addition of monospace messages is also really neat! Again, I don't really have a working program to look at at the moment so I'm basing my opinions on screenshots I took and your recent commits.

I would be really grateful for any credit honestly! You can use my name (Balázs Cene) and the username I use here for it. Thank you for letting me help here, and if you have anything similar in the future I'd happily give my 2 cents again!

**Comment by bczsalba** [comment]
Update: Something fixed the issues I was having, and I stand by my opinions above. The open/save dialogues work perfectly here as well:
<img width="440" alt="Screenshot 2022-01-24 at 9 06 59" src="https://user-images.githubusercontent.com/66030897/150744677-82d7dab6-014c-4920-95b7-2a4254c2ec0d.png">

<img width="372" alt="Screenshot 2022-01-24 at 9 07 27" src="https://user-images.githubusercontent.com/66030897/150744730-ae780aa0-c20a-49a0-9daf-18f282003429.png">

...and #18 seems to be happening here as well.
Anyways, great work!

**Comment by STBoyden** [comment]
Great, thank you! Look for your name in the credits soon! :)

**Comment by STBoyden** [comment]
Merging now
