### ISSUE TITLE
Add a way to save the session.

### ISSUE THREAD

**Issue by svmorris** [pwnCTRL/codectrl#17]
Usually this is not that important, but when working on larger targets for multiple days it could be incredibly useful if the GUI could save all the logs in some sort of save file. Then when you come back to a project a little bit later you can see all the things you have been working on and pick up from where you left off.

**Comment by STBoyden** [comment]
This was implemented in the 1103d7b4683d3b299d72ae88b6c0642d7edac1e0 commit.
