### ISSUE TITLE
The message is a bit hard to see (imo)

### ISSUE THREAD

**Issue by svmorris** [pwnCTRL/codectrl#19]
I think the message is generally more important than the rest of the data in the logger, and when you have a lot, but not enough for it to become a popup, it is a bit hard to read.

We could perhaps make it bold, accent colour, or some code-block style design like `message_type` has? Or anything else to increase contrast and make the message stand out more.

An example of the problem:
![Image of message being hard to read](https://user-images.githubusercontent.com/46561460/150643496-d9bcba3a-43d7-4bdb-a0b0-5d096a15edda.png)

**Comment by STBoyden** [comment]
> We could perhaps make it bold, accent colour, or some code-block style design like `message_type` has? Or anything else to increase contrast and make the message stand out more.

As mentioned in the #15 issue, it'd probably be better to avoid it being bold or higher contrast in someway unless it's explicitly interactable.

![image](https://user-images.githubusercontent.com/25185976/150648311-97a8102a-7cd2-46e2-9ba1-3af1db4e95dd.png)

Is that better?

**Comment by svmorris** [comment]
yea that is perfect, thank you :slightly_smiling_face:
