### ISSUE TITLE
"Master" settings for logs on the control panel.

### ISSUE THREAD

**Issue by svmorris** [pwnCTRL/codectrl#2]
When a library connects to the server the server could send settings to the library about what information to collect/send. This would allow for a central control panel to managing what information gets to the server. 

Settings could eg be things like: how many lines of code should it collect from around the log function.

The settings that the server sends could either be a default or an override to arguments passed as function parameters. 
(I am leaning slightly towards override but I'm not sure and either is good)

**Comment by STBoyden** [comment]
Will come back to this later, at this point it is a bit of a pain to implement.
