### ISSUE TITLE
Design idea for the main control panel

### ISSUE THREAD

**Issue by svmorris** [pwnCTRL/codectrl#3]
I have sketched up the design Idea I was trying to showcase on the business meeting. 

By all means you don't have to do this idea, or you don't have to do anything close to it even. This is just one possible idea of how I imagined the design of the control pane
![Screenshot from 2021-11-10 17-21-57](https://user-images.githubusercontent.com/46561460/141162113-a6f91612-ccdf-47ed-835b-b5e0d9aa5735.png)

**Comment by STBoyden** [comment]
Started work on this in ddef023. Currently WIP

**Comment by STBoyden** [comment]
Should be finishing up on this issue soon.
